flask/useradvocacy/reports/models.py
# -*- coding: utf-8 -*-
import datetime as dt
from useradvocacy.user.models import User
from flask import current_app
from sqlalchemy import text

from useradvocacy.database import (
    Column,
    db,
    Model,
    ReferenceCol,
    relationship,
    SurrogatePK,
)

from .markdown2html import convert_md, get_md_meta

def make_filename(context):
    return context.current_parameters['name'] + '.html'

class Template(SurrogatePK, Model):
    __tablename__ = 'templates'
    name = Column(db.String(length=200), unique=True, nullable=False)
    filename = Column(db.String(length=200), unique=False, nullable=False)
    created = Column(db.DateTime, nullable=False, default=dt.datetime.utcnow)
    md_content = Column(db.Text(), unique=False, nullable=False)

    def __init__(self, name, **kwargs):
        db.Model.__init__(self, name=name, **kwargs)

    def __repr__(self):
        return '<Template ({name})>'.format(name=self.name)
        
    def __str__(self):
        return self.name;

class Report(SurrogatePK, Model):

    __tablename__ = 'reports'
    project = Column(db.String(length=200), nullable=False)
    filename = Column(db.String(length=200), nullable=False)
    title = Column(db.String(length=1000), nullable=True)
    md_content = Column(db.Text(), unique=False, nullable=False)
    html_content = Column(db.Text(), unique=False, nullable=False)
    author_id = ReferenceCol('users')
    author = db.relationship('User', backref='users', lazy='joined')
    listed = Column(db.Boolean(), nullable=False, default=True)
    published = Column(db.Boolean(), nullable=False, default=False)
    created = Column(db.DateTime, nullable=False, default=dt.datetime.utcnow)
    updated = Column(db.DateTime, nullable=False, default=dt.datetime.utcnow, onupdate=dt.datetime.utcnow)
    template_id = ReferenceCol('templates')
    template = db.relationship('Template', backref='reports', lazy='joined')
    
    def __init__(self, filename, project, md_content, template_id=1, **kwargs):
        db.Model.__init__(self, filename=filename, project=project, template_id=template_id, md_content = md_content, html_content="blank",  **kwargs)
        
            
    def __repr__(self):
        return '<Report({project!s}/{filename!s})>'.format(project=self.project, filename=self.filename)
    
    def save_render_html(self):
        print 'Rendering ({project!s}/{filename!s})'.format(project=self.project, filename=self.filename)
        env = current_app.create_jinja_environment()
        template_file = env.get_template(self.template.filename)
        if self.published:
            html = convert_md(self.md_content, template_file)
        else:
            warn_msg = "This file not published and only visible to UA team."
            html = convert_md(self.md_content, template_file, warning=warn_msg)
        meta = get_md_meta(self.md_content)
        title_known = ''
        if (not "title" in meta or meta["title"] == ''):
            title_known = self.project + "/" + self.filename
        else:
            title_known = meta["title"]
        self.update(html_content = html)
        self.update(title = title_known)
        self.save()
        return
    
    def __str__(self):
        return '{project!s}/{filename!s}'.format(project=self.project, filename=self.filename)
        
    @property
    def shown(self):
        return (self.listed and self.published)

flask/useradvocacy/dashboards/__init__.py
# -*- coding: utf-8 -*-
'''The dashboards module.'''

from . import views
from flask import Flask

app = Flask(__name__)

flask/useradvocacy/dashboards/views.py
# -*- coding: utf-8 -*-

'''
Serve static files/folders that we check in as dashboards.
TODO: Add templates to served pages to give everything a nice consistent look

'''

from flask import (current_app, Flask, Blueprint, request, render_template, url_for, flash, redirect, session, send_from_directory, safe_join, Response)
from werkzeug.exceptions import Unauthorized, Forbidden, NotFound, BadRequest, Conflict
from useradvocacy.utils import flash_errors, check_admin
import os
import re
import flask.json
from functools import wraps
from werkzeug.utils import secure_filename
import shutil

from flask.ext.login import login_required


blueprint = Blueprint('dashboards', __name__, static_folder="./static", 
        url_prefix="/dashboards", template_folder=".")

@blueprint.route("/", methods=["GET"])
def home():
    try:
        return render_template('templates/dashboards.html')
    except IOError:
        raise NotFound

@blueprint.route("static/css/<file>", methods=["GET"])
def serve_css(file):
    return send_from_directory(safe_join(current_app.root_path, "dashboards/static/css"), file)
    
@blueprint.route("static/img/<file>", methods=["GET"])
def serve_img(file):
    return send_from_directory(safe_join(current_app.root_path, "dashboards/static/img"), file)
    
@blueprint.route("static/js/<file>", methods=["GET"])
def serve_js(file):
    return send_from_directory(safe_join(current_app.root_path, "dashboards/static/js"), file)

@blueprint.route("/<name>/", methods=["GET"])
def dash_server(name):
    try:
        return render_template(safe_join(safe_join("files",name),"index.html"))
    except IOError:
        raise NotFound
    
@blueprint.route("/<name>/<file>.html", methods=["GET"])
def dash_html_server(name, file):
    try:
        return render_template(safe_join(safe_join("files",name),file + ".html"))
    except IOError:
        raise NotFound

@blueprint.route("/<name>/<file>", methods=["GET"])
def file_server(name, file):
    return send_from_directory(safe_join(safe_join(current_app.root_path, 'dashboards/files'), name), file)

flask/useradvocacy/reports/__init__.py
# -*- coding: utf-8 -*-
'''The reports module.'''

from . import views
from flask import Flask

app = Flask(__name__)

flask/useradvocacy/reports/views.py
# -*- coding: utf-8 -*-

'''Templating engine for reports'''


from flask import (current_app, Flask, Blueprint, request, render_template, url_for, flash, redirect, session, send_from_directory, safe_join, Response, jsonify)
from werkzeug.exceptions import Unauthorized, Forbidden, NotFound, BadRequest, Conflict
                    
from useradvocacy.extensions import login_manager
from flask.ext.login import current_user
from useradvocacy.user.models import User
from useradvocacy.database import db
from useradvocacy.reports.models import User, Template, Report
from .forms import EditorForm, SelectorForm, PreviewForm
from useradvocacy.utils import flash_errors, check_admin
import os
import re
import flask.json
from functools import wraps
from werkzeug.utils import secure_filename
from .markdown2html import convert_md
import shutil

from flask.ext.login import login_required

blueprint = Blueprint('reports', __name__, static_folder="./static", 
        url_prefix="/reports", template_folder="./templates")

def upload_path():
    if current_app.config['UPLOAD_PATH']:
        upload = os.path.join(current_app.config['UPLOAD_PATH'], 'reports')
    else:
        upload = os.path.join(current_app.root_path, 'reports', 'uploads')
    print upload
    return upload

def validate_project_filename(fn):
    @wraps(fn)
    def new_fn(project, filename, *args, **kwargs):
        if re.match('[a-zA-Z0-9_-]+$',project) or re.match('[a-zA-Z0-9_-]+$',filename):
            return fn(project, filename, *args, **kwargs)
        else:
            raise BadRequest()
    return new_fn
    

def allowed_file(name):
    if re.match('[^/.\'\\\\"]+\\.(css|js|png|jpg|jpeg|gif|json|csv|tsv|xml|pdf|key)$', name, flags=re.IGNORECASE):
        return True
    else:
        return False

@blueprint.route("/", methods=["GET"])
def home():
    reports = Report.query.order_by("updated").all()
    reports.reverse()
    projects = db.session.query(Report.project.label('name'), db.func.bit_or(db.and_(Report.published, Report.listed)).label('shown')).group_by('name').all()
    print projects[0].shown
    return render_template('reports.html', list = reports, projects = projects)

@blueprint.route("/css/<file>", methods=["GET"])
def serve_css(file):
    return send_from_directory(safe_join(current_app.root_path, "reports/static/css"), file)
    
@blueprint.route("/img/<file>", methods=["GET"])
def serve_img(file):
    return send_from_directory(safe_join(current_app.root_path, "reports/static/img"), file)
    
@blueprint.route("/js/<file>", methods=["GET"])
def serve_js(file):
    return send_from_directory(safe_join(current_app.root_path, "reports/static/js"), file)

@blueprint.route("/edit", methods=["GET", "POST"])
@login_required
@check_admin
def selector():
    form = SelectorForm()
    if request.method == 'POST':
        if form.validate_on_submit():
            if form.action == "report":
                return redirect('/reports/' + form.project + '/' + form.filename 
                    + '/edit', 302)
            if form.action == "rerender":
                reports = Report.query.all()
                for report in reports:
                    report.save_render_html()
        else:
            flash_errors(form)
    return render_template('selector.html',form=form)

# TODO: rewrite API.json to take parameters instead of just returning.
# TODO: return metadata along with individual reports.
# (see also: home_project_api())

@blueprint.route("/api.json", methods=["GET"])
def home_api():
    reports = Report.query.order_by("updated").limit(100).all()
    result = []
    for report in reports:
        if (not (current_user and current_user.is_authenticated() and
            current_user.is_admin)
            and not report.published):
            continue
        item = {
            'path'      : url_for(".home") + str(report),
            'filename'  : report.filename,
            'project'   : report.project,
            'created'   : report.created,
            'updated'   : report.updated,
            'title'     : report.title
        }
        result.append(item)
    return jsonify(results = result)

@blueprint.route("/<project>/", methods=["GET"])
def home_project(project):
    return redirect(url_for(".home") + "#" + project)

@blueprint.route("/<project>/api.json", methods=["GET"])
def home_project_api(project):
    reports = Report.query.filter_by(project = project).order_by("updated").all()
    result = []
    for report in reports:
        if (not (current_user and current_user.is_authenticated() and
            current_user.is_admin)
            and not report.published):
            continue
        item = {
            'path'      : url_for(".home") + str(report),
            'filename'  : report.filename,
            'project'   : report.project,
            'created'   : report.created,
            'updated'   : report.updated,
            'title'     : report.title
        }
        result.append(item)
    return jsonify(results = result)


@blueprint.route("/<project>/<filename>/", methods=["GET", "POST"])
@validate_project_filename
def display(project, filename):
    report = Report.query.filter_by(filename = filename, project = project).first()
    if report:
        if report.published or (not current_user.is_anonymous() and
            current_user.is_admin):
            return report.html_content
        else:
            raise NotFound()
    else:
        raise NotFound()

@blueprint.route("/<project>/<filename>/edit", methods=["GET", "POST"])
@validate_project_filename
@login_required
@check_admin
def edit(project, filename):
    template_name = request.args.get('template', 'default')
    report = Report.query.filter_by(project = project, filename = filename).first()
    default_template = Template.query.filter_by(name = template_name).first()
    form = None
    if report:
        form = EditorForm(project_field=project, filename_field=filename, 
            template_field = report.template, markdown_field=report.md_content,
            published_field = report.published, listed_field = report.listed)
    else:
        form = EditorForm(project_field=project, filename_field=filename, 
            template_field = default_template, markdown_field=default_template.md_content)
    if request.method == 'POST':
        if form.validate_on_submit():
            save_user = None
            if current_user.is_anonymous():
                save_user = User.query.filter_by(username="<blank>").first()
            else:
                save_user = current_user
            if form.savemode is 'save':
                report = Report.query.filter_by(filename = form.filename, 
                    project = form.project).first()
                if report:
                    report.update(template_id = form.template.id, 
                        md_content = form.md_content,
                        listed = form.listed,
                        published = form.published)
                    flash("Report saved.", 'success')
                else:
                    report = Report.create(filename = form.filename, 
                        project = form.project, template = form.template, 
                        md_content = form.md_content, author = save_user,
                        listed = form.listed, published = form.published)
                    flash("New report created and saved!", 'success')
                report.save_render_html()
                form = EditorForm(project_field=form.project,
                    filename_field=form.filename, template_field=form.template,
                    markdown_field = form.md_content, listed_field = form.listed,
                    published_field = form.published)
            elif form.savemode is "saveas":
                report = Report.create(filename = form.filename, 
                    project = form.project, template = form.template, 
                    md_content = form.md_content, author = save_user,
                    listed = form.listed, published = form.published)
                report.save_render_html()
                old_path = os.path.join(upload_path(), form.old_project,
                    form.old_filename)
                new_path = os.path.join(upload_path(), form.project,
                    form.filename)
                # Move files along with copying data
                try:
                    files = os.listdir(old_path)
                except OSError:
                    pass
                else:
                    if os.path.exists(new_path):
                        flash("Files not copied!", 'error')
                    else:
                        shutil.copytree(old_path, new_path)
                        flash("Files copied!", 'success')
                flash("New report created and saved!", 'success')
                return redirect("/reports/" + form.project + "/" + 
                    form.filename + "/edit", 303)
            else:
                assert False
        else:
            flash_errors(form)
    preview_form = PreviewForm(markdown_preview_field = '', template_preview_field = '')
    return render_template('editor.html',form=form, project=project, 
        filename=filename, preview_form=preview_form)

@blueprint.route("/<project>/<filename>/upload", methods=["POST"])
@validate_project_filename
@login_required
@check_admin
def upload_file(project, filename):
    file = request.files['file']
    if file and allowed_file(file.filename):
        file_save = secure_filename(file.filename)
        try:
            os.makedirs(os.path.join(upload_path(), project, filename))
        except OSError:
            pass
        try:
            file.save(os.path.join(upload_path(), project, filename, file_save))
        except (IOError, OSError) as err:
            raise Conflict("Can't save file: " + err.strerror)
            flash("Can't save file: " + err.strerror, 'error')
        else:
            return "File uploaded", 200   

flask/useradvocacy/reports/templates/dashboard.html
<!doctype html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<head>
  <meta charset="utf-8">

  <title>{% block page_title %}

    UA Server

    {% endblock %}
  </title>
  <meta name="description" content="{% block meta_description %}{% endblock %}">
  <meta name="author" content="{% block meta_author %}{% endblock %}">

  <!-- Mobile viewport optimized: h5bp.com/viewport -->
  <meta name="viewport" content="width=device-width">

  <link rel="stylesheet" href="{{ url_for('static', filename='libs/font-awesome/css/font-awesome.min.css') }}"/>
    <link rel="stylesheet" href="{{ url_for('static', filename='libs/bootstrap/dist/css/bootstrap.min.css') }}"/>
<link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}"/>
<link href="{{ url_for('static', filename='css/charts.css') }}" rel="stylesheet"/>
    {% if css %}
    <link rel="stylesheet" type="text/css" href="{{css}}" />
    {% endif %}
</head>
<body class="{% block body_class %}{% endblock %}">
{% block body %}
{% with form=form  %}
{% include "nav.html" %}
{% endwith %}
{% if warning %}
<div class="warning-banner">{{ warning }}</div>
{% endif %}
<div class="{% block content_class %}container{% endblock content_class %}">

  <div role="main">
<div class="container">
<h2>{{title}}</h2>
{{content|safe}}
</div>
</div>

</div><!-- end container -->

{% include "footer.html" %}

<!-- JavaScript at the bottom for fast page loading -->

    <script src="{{ url_for('static', filename='libs/jQuery/dist/jquery.min.js') }}"></script>
    <script src="{{ url_for('static', filename='libs/d3/d3.min.js') }}"></script>
    <script src="{{ url_for('static', filename='libs/lodash/lodash.js') }}"></script>
    <script src="{{ url_for('static', filename='js/d3promise.js') }}"></script>
    <script src="{{ url_for('static', filename='js/charts.js') }}"></script>
    {% if js %}
    <script src="{{js}}"></script>
    {% endif %}
<!-- end scripts -->
{% endblock %}
</body>
</html>

flask/useradvocacy/reports/templates/default.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">

<head>
<link href='http://fonts.googleapis.com/css?family=Philosopher:400,400italic,700,700italic|Lemon|Lobster+Two:400,400italic,700,700italic' rel='stylesheet' type='text/css'>
<link rel="stylesheet" type="text/css" href="{{ url_for('reports.serve_css', file='default-styles.css') }}" />
{% if css %}
<link rel="stylesheet" type="text/css" href="{{css}}" />
{% endif %}

<script src="{{ url_for('static', filename='libs/d3/d3.min.js') }}"></script>
<script src="{{ url_for('static', filename='js/charts.js') }}"></script>
<script src="{{ url_for('static', filename='libs/jQuery/dist/jquery.min.js') }}"></script>

<meta charset="UTF-8">
<title>User Advocacy - {{title}}</title>
</head>
<body> 

<div class="holder">
{% if warning %}
<div class="warning-banner">{{ warning }}</div>
{% endif %}
	<div class="center-block">
 
 		<div class="header">
		<!--Start Tab Image -->

            <a href="http://mozilla.org/" class="moz-image" target="_blank" style="moz-image" title="mozilla tab">
            <img src="../../img/j3h2kggt.png"  alt="Mozilla" align="right" border="0" style="display:block" height="42" width="147"/></a>
      <!--End Tab Image -->
			
      
      <!--Start Title info -->   
            <a href="{{ url_for('public.home')}}" id="wordmark"><span class="large-grey-text">User</span><span class="large-red-text">Advocacy</span></a>
            <div class="subheader">
                    <div class="date-line">{{date}}</div>
                    <div class="email-line">Questions? Comments? Email: <a href="mailto:{{email}}">{{author}}</a></div>
            </div>
            <h1>{{title}}</h1>
       <!--End title info -->

</div>
<div class="content">
{{content|safe}}
</div>
      <!--Start footer -->

      <div class="footer">

      </div>
			

<!--End footer -->

  </div>
  </div>

</body>
<script src="../../js/default.js"></script>
<script src="{{ url_for('static', filename='libs/lodash/lodash.js') }}"></script>
</html>

flask/useradvocacy/reports/templates/editor.html
{% extends "layout.html" %} 
{% block css %}
<link rel="stylesheet" href="../../css/dropzone.css">
{% endblock %}
{% block content %} 


    <form method = "POST"> 
    {{ form.csrf_token() }} {{ form.project_field() }} {{ form.filename_field() }}

<h3> Now editing: {{ project }}/{{ filename }}</h3>

<div class="row" style="margin-bottom: 5px">
<div class="col-sm-1">
{{ form.template_field.label }}:
</div>
<div class="col-sm-2">
{{ form.template_field(class="form-control input-sm") }}
</div>
<div class="col-sm-3">
<label class="btn btn-default btn-sm" title="Whether this page is visible outside the team (overrides Listed)">
{{ form.published_field(class="check-button", id="publish-button") }}
Published
</label>
<label class="btn btn-default btn-sm" title="Whether to show in the Reports listing (only applies if Published)">
{{ form.listed_field(class="check-button", id="listed-button") }}
Listed
</label>
</div>
</div>
<div class="row">
<div class="col-lg-6" id="edit-box">
{{ form.markdown_field.label }}: <a href="#" class="btn btn-default btn-xs preview-show" onclick="submit_preview()" style="display: none">preview in new tab <i class="fa fa-external-link"></i></a>
<a href="#" class="btn btn-default btn-xs preview-noshow pull-right" onclick="submit_preview()">preview now <i class="fa fa-share-square-o"></i></a>
<a href="#" class="btn btn-default btn-xs preview-show pull-right" onclick="show_preview()" style="display: none">show preview <i class="fa fa-chevron-right"></i></a><br/>
{{ form.markdown_field(class="main_md form-control", style="height: 450px; font-family: monospace; width: 100%") }}
</div>
<div class="col-lg-6" id="preview-box">
<span style="cursor: pointer;" onclick="submit_preview()">
<strong>Preview:</strong>
</span> 
<a href="#" class="btn btn-default btn-xs pull-right" onclick="hide_preview()"><i class="fa fa-chevron-left"></i> hide preview</a>
<iframe src="" id="preview-area" style="height:450px; width: 100%; border: 0;" name="preview-frame">
Insert preview here
</iframe>
</div>
</div>
<div class="row">
    <div class="col-md-4">
    <h4> Save this as a new report... </h4>
        <div class="row">
        <div class="col-sm-6">{{ form.new_project_field.label(class="sr-only") }}
        {{ form.new_project_field(class="form-control input-sm", placeholder="Project") }}</div><div class="col-sm-6">{{ form.new_filename_field.label(class="sr-only") }}{{ form.new_filename_field(class="form-control input-sm", placeholder="Filename") }}</div></div><div class="row" style="margin-top: 10px"><div class="col-xs-2 col-xs-offset-9">
{{ form.saveas_button(class="btn-sm btn btn-warning") }}  </div></div></div>
    <div class="col-sm-4 col-sm-offset-1">
        <h4>Or you can ... </h4> {{ form.save_button(class="btn-sm btn btn-success") }} <h4> and <a href = "/reports/{{ project }}/{{ filename }}/" target = "_blank"> go to your report </a>.</h4> </div></div>

</div>
</form>
<div class="col-md-10 col-md-offset-1">
<h4> You have the following files associated with this document (drag files in): </h4>
<div id="uploader" class="dropzone" style="margin-top: 20px;">
</div></div>

    <!-- Dummy form for handling previews -->
    <form id="preview" action="preview" method="POST" target="preview-frame"> {{ preview_form.markdown_preview_field() }} 
{{ preview_form.template_preview_field() }} </form>
{% endblock %}
{% block js %}
<script src="../../js/dropzone.js"></script>
<script src="../../js/editor.js"></script>
{% endblock %}

flask/useradvocacy/reports/templates/reports.html
{% extends "layout.html" %}

{% block css %}
<link rel="stylesheet" href="css/reports.css">
{% endblock %}

{% block content %}
<div class="container-narrow">
<h2><span class="fa-stack fa">
  <i class="fa fa-circle fa-stack-2x"></i>
  <i class="fa fa-file-text fa-stack-1x fa-inverse"></i>
</span>User Advocacy Reports</h2>
<p>Have questions? Need a report for one of your projects? Contact your friendly local UA team member today!</p>
</div>
<div class="container-medium">
<div class="row">
<div class='col-sm-3'>
<div class='hidden-xs' id='sidebar-filter'>
<h4>Filters:</h4>
<div class="btn-group-vertical">
<a class="btn btn-default side-filter" href="#" id="filter-All">All</a>
{% for proj in projects if ((current_user and current_user.is_authenticated() and current_user.is_admin) or proj.shown) %}
<a class="btn btn-default side-filter" href="#{{ proj.name }}" id="filter-{{ proj.name }}">{{ proj.name }}</a>
{% endfor %}
</div>
</div>
</div>
<div class="list-group report-list col-sm-9">
<div class='hidden-sm hidden-md hidden-lg' id='top-filter'>
<strong>Filter:</strong>
<div class='btn-group'>
<button type="button" class="btn btn-default dropdown-toggle btn-sm" data-toggle="dropdown" id="filter-button">
<span id="filter-menu" class="text-info">All</span> <span class="caret"></span>
</button>
<ul class="dropdown-menu" role="menu">
<li id="fbutton-All"><a class="" href="#">All</a></li>
{% for proj in projects if ((current_user and current_user.is_authenticated() and current_user.is_admin) or proj.shown) %}
<li id="fbutton-{{ proj.name }}"><a class="" href="#{{ proj.name }}">{{ proj.name }}</a></li>
{% endfor %}
</div>
</div>
<div class="jumbotron" id="empty-warning"><p class="text-center">I find your lack of reports disturbing.</p></div>
{% for item in list if ((current_user and current_user.is_authenticated() and current_user.is_admin) or item.shown) %}
<div class="list-group-item report-item report-item-{{ item.project }}" onclick="location.href='{{ item.project }}/{{ item.filename }}'">
{% if current_user and current_user.is_authenticated() and current_user.is_admin %}
<a href="{{ item.project }}/{{ item.filename }}/edit" class="edit-link"><i class="fa fa-edit text-info"></i></a>
{% endif %}
<span class="label label-default pull-right">{{ item.project }}</span>
{{ item.title }}
{% if not item.published %}
<span class="small text-danger">(not&nbsp;published)</span>
{% elif not item.listed %}
<span class="small text-warning">(not&nbsp;listed)</span>
{% endif %}
</div>
{% endfor %}
</div>
</div>
</div>
{% endblock %}
{% block js %}
<script src="js/reports.js"></script>
{% endblock %}

flask/useradvocacy/reports/templates/selector.html
{% extends "layout.html" %}

{% block content %}

<form method="POST" class="form-inline">
{{ form.csrf_token() }}
<div class="container-narrow">
{% if current_user and current_user.is_authenticated() %}
<h3>Hi, {{ current_user.username }}!</h3>
{% endif %}
<h3>Do you want to open a recent report...</h3>

{{ form.project_filename.label }}: {{ form.project_filename(class="form-control") }} {{ form.go_button(class="btn-sm btn btn-default")}}
<h3>Or create a new one...</h3>
{{ form.new_project_field.label(class="sr-only") }}{{ form.new_project_field(class="form-control", placeholder="Project") }} / {{ form.new_filename_field.label(class="sr-only") }}{{ form.new_filename_field(class="form-control", placeholder="Filename") }}
{{ form.saveas_button(class="btn-sm btn btn-default") }} 
<h3>Or do something else?</h3>
{{ form.rerender_button(class="btn-sm btn btn-default") }} 
</div>
</form>
{% endblock %}