flask/useradvocacy/app.py
# -*- coding: utf-8 -*-
'''The app module, containing the app factory function.'''
from flask import Flask, render_template

from useradvocacy.settings import ProdConfig
from useradvocacy.assets import assets
from useradvocacy.extensions import (
    bcrypt,
    cache,
    db,
    login_manager,
    migrate,
    debug_toolbar,
)
from useradvocacy import public, user, reports, dashboards, data


def create_app(config_object=ProdConfig):
    '''An application factory, as explained here:
        http://flask.pocoo.org/docs/patterns/appfactories/

    :param config_object: The configuration object to use.
    '''
    app = Flask(__name__)
    app.config.from_object(config_object)
    register_extensions(app)
    register_blueprints(app)
    register_errorhandlers(app)
    return app


def register_extensions(app):
    assets.init_app(app)
    bcrypt.init_app(app)
    cache.init_app(app) 
    db.init_app(app)
    login_manager.init_app(app)
    debug_toolbar.init_app(app)
    migrate.init_app(app, db)
    return None

# Insert new apps here

def register_blueprints(app):
    app.register_blueprint(public.views.blueprint)
    app.register_blueprint(user.views.blueprint)
    app.register_blueprint(reports.views.blueprint)
    app.register_blueprint(dashboards.views.blueprint)
    app.register_blueprint(data.views.blueprint)
    return None


def register_errorhandlers(app):
    def render_error(error):
        # If a HTTPException, pull the `code` attribute; default to 500
        error_code = getattr(error, 'code', 500)
        return render_template("{0}.html".format(error_code)), error_code
    for errcode in [401, 404, 500]:
        app.errorhandler(errcode)(render_error)
    return None

flask/useradvocacy/dashboards/__init__.py
# -*- coding: utf-8 -*-
'''The dashboards module.'''

from . import views
from flask import Flask

app = Flask(__name__)

flask/useradvocacy/dashboards/views.py
# -*- coding: utf-8 -*-

'''
Serve static files/folders that we check in as dashboards.
TODO: Add templates to served pages to give everything a nice consistent look

'''

from flask import (current_app, Flask, Blueprint, request, render_template, url_for, flash, redirect, session, send_from_directory, safe_join, Response)
from werkzeug.exceptions import Unauthorized, Forbidden, NotFound, BadRequest, Conflict
from useradvocacy.utils import flash_errors, check_admin
import os
import re
import flask.json
from functools import wraps
from werkzeug.utils import secure_filename
import shutil

from flask.ext.login import login_required


blueprint = Blueprint('dashboards', __name__, static_folder="./static", 
        url_prefix="/dashboards", template_folder=".")

@blueprint.route("/", methods=["GET"])
def home():
    try:
        return render_template('templates/dashboards.html')
    except IOError:
        raise NotFound

@blueprint.route("static/css/<file>", methods=["GET"])
def serve_css(file):
    return send_from_directory(safe_join(current_app.root_path, "dashboards/static/css"), file)
    
@blueprint.route("static/img/<file>", methods=["GET"])
def serve_img(file):
    return send_from_directory(safe_join(current_app.root_path, "dashboards/static/img"), file)
    
@blueprint.route("static/js/<file>", methods=["GET"])
def serve_js(file):
    return send_from_directory(safe_join(current_app.root_path, "dashboards/static/js"), file)

@blueprint.route("/<name>/", methods=["GET"])
def dash_server(name):
    try:
        return render_template(safe_join(safe_join("files",name),"index.html"))
    except IOError:
        raise NotFound
    
@blueprint.route("/<name>/<file>.html", methods=["GET"])
def dash_html_server(name, file):
    try:
        return render_template(safe_join(safe_join("files",name),file + ".html"))
    except IOError:
        raise NotFound

@blueprint.route("/<name>/<file>", methods=["GET"])
def file_server(name, file):
    return send_from_directory(safe_join(safe_join(current_app.root_path, 'dashboards/files'), name), file)

flask/useradvocacy/data/__init__.py
# -*- coding: utf-8 -*-
'''The data module. This connects to data databases and returns data'''

from . import views
from flask import Flask

app = Flask(__name__)

flask/useradvocacy/data/views.py
# -*- coding: utf-8 -*-

'''Server data access endpoints'''

import os
import traceback

import flask.json
from flask import (current_app, Flask, Blueprint, request, render_template, url_for, flash, redirect, session, send_from_directory, safe_join, Response)
from flask.ext.login import current_user
from flask.ext.login import login_required
from functools import wraps

from werkzeug.exceptions import Unauthorized, Forbidden, NotFound, BadRequest, Conflict
from werkzeug.datastructures import MultiDict

from useradvocacy.user.models import User
from useradvocacy.database import db
from useradvocacy.extensions import login_manager
from useradvocacy.utils import flash_errors, check_admin, nocache, jsonerror

from .stats import stats_return
from .heartbeat_stats import heartbeat_stats_return
from .telemetry import telemetry_stats, telemetry_stat, telemetry_params



blueprint = Blueprint('data', __name__, static_folder="./static",
        url_prefix="/data", template_folder="./templates")

@nocache
@blueprint.route("/api/v1/stats", methods=["GET"])
@jsonerror
def stats_api():
    args = parse_args(request.args)
    ret = stats_return(args)
    return ret

@nocache
@blueprint.route("/api/v1/heartbeat_stats", methods=["GET"])
@jsonerror
def heartbeat_stats_api():
    args = parse_args(request.args)
    ret = heartbeat_stats_return(args) #TODO(rrayborn)
    return ret

@nocache
@blueprint.route("/api/v1/telemetry/params", methods=["GET"])
@jsonerror
def telemetry_params_api():
    return telemetry_params()

@nocache
@blueprint.route("/api/v1/telemetry", methods=["GET"])
@jsonerror
def telemetry_stats_api():
    args = parse_args(request.args)
    ret = telemetry_stats(args)
    return ret

@nocache
@blueprint.route("/api/v1/telemetry_stat", methods=["GET"])
@jsonerror
def telemetry_stat_api():
    args = parse_args(request.args)
    ret = telemetry_stat(args)
    return ret

@blueprint.route("/static/json/<file>", methods=["GET"])
def json_server(file):
    return send_from_directory(os.path.join(current_app.root_path, 'data', 'static_json'), file)

def parse_args(raw_args):
    args = MultiDict()
    for (arg_name, arg_outer_values) in raw_args.iterlists():
        for arg_inner_values in arg_outer_values:
            for arg_value in arg_inner_values.split(','):
                args.add(arg_name, arg_value.strip())
    return args

flask/useradvocacy/reports/__init__.py
# -*- coding: utf-8 -*-
'''The reports module.'''

from . import views
from flask import Flask

app = Flask(__name__)

flask/useradvocacy/reports/views.py
# -*- coding: utf-8 -*-

'''Templating engine for reports'''


from flask import (current_app, Flask, Blueprint, request, render_template, url_for, flash, redirect, session, send_from_directory, safe_join, Response, jsonify)
from werkzeug.exceptions import Unauthorized, Forbidden, NotFound, BadRequest, Conflict
                    
from useradvocacy.extensions import login_manager
from flask.ext.login import current_user
from useradvocacy.user.models import User
from useradvocacy.database import db
from useradvocacy.reports.models import User, Template, Report
from .forms import EditorForm, SelectorForm, PreviewForm
from useradvocacy.utils import flash_errors, check_admin
import os
import re
import flask.json
from functools import wraps
from werkzeug.utils import secure_filename
from .markdown2html import convert_md
import shutil

from flask.ext.login import login_required

blueprint = Blueprint('reports', __name__, static_folder="./static", 
        url_prefix="/reports", template_folder="./templates")

def upload_path():
    if current_app.config['UPLOAD_PATH']:
        upload = os.path.join(current_app.config['UPLOAD_PATH'], 'reports')
    else:
        upload = os.path.join(current_app.root_path, 'reports', 'uploads')
    print upload
    return upload

def validate_project_filename(fn):
    @wraps(fn)
    def new_fn(project, filename, *args, **kwargs):
        if re.match('[a-zA-Z0-9_-]+$',project) or re.match('[a-zA-Z0-9_-]+$',filename):
            return fn(project, filename, *args, **kwargs)
        else:
            raise BadRequest()
    return new_fn
    

def allowed_file(name):
    if re.match('[^/.\'\\\\"]+\\.(css|js|png|jpg|jpeg|gif|json|csv|tsv|xml|pdf|key)$', name, flags=re.IGNORECASE):
        return True
    else:
        return False

@blueprint.route("/", methods=["GET"])
def home():
    reports = Report.query.order_by("updated").all()
    reports.reverse()
    projects = db.session.query(Report.project.label('name'), db.func.bit_or(db.and_(Report.published, Report.listed)).label('shown')).group_by('name').all()
    print projects[0].shown
    return render_template('reports.html', list = reports, projects = projects)

@blueprint.route("/css/<file>", methods=["GET"])
def serve_css(file):
    return send_from_directory(safe_join(current_app.root_path, "reports/static/css"), file)
    
@blueprint.route("/img/<file>", methods=["GET"])
def serve_img(file):
    return send_from_directory(safe_join(current_app.root_path, "reports/static/img"), file)
    
@blueprint.route("/js/<file>", methods=["GET"])
def serve_js(file):
    return send_from_directory(safe_join(current_app.root_path, "reports/static/js"), file)

@blueprint.route("/edit", methods=["GET", "POST"])
@login_required
@check_admin
def selector():
    form = SelectorForm()
    if request.method == 'POST':
        if form.validate_on_submit():
            if form.action == "report":
                return redirect('/reports/' + form.project + '/' + form.filename 
                    + '/edit', 302)
            if form.action == "rerender":
                reports = Report.query.all()
                for report in reports:
                    report.save_render_html()
        else:
            flash_errors(form)
    return render_template('selector.html',form=form)

# TODO: rewrite API.json to take parameters instead of just returning.
# TODO: return metadata along with individual reports.
# (see also: home_project_api())

@blueprint.route("/api.json", methods=["GET"])
def home_api():
    reports = Report.query.order_by("updated").limit(100).all()
    result = []
    for report in reports:
        if (not (current_user and current_user.is_authenticated() and
            current_user.is_admin)
            and not report.published):
            continue
        item = {
            'path'      : url_for(".home") + str(report),
            'filename'  : report.filename,
            'project'   : report.project,
            'created'   : report.created,
            'updated'   : report.updated,
            'title'     : report.title
        }
        result.append(item)
    return jsonify(results = result)

@blueprint.route("/<project>/", methods=["GET"])
def home_project(project):
    return redirect(url_for(".home") + "#" + project)

@blueprint.route("/<project>/api.json", methods=["GET"])
def home_project_api(project):
    reports = Report.query.filter_by(project = project).order_by("updated").all()
    result = []
    for report in reports:
        if (not (current_user and current_user.is_authenticated() and
            current_user.is_admin)
            and not report.published):
            continue
        item = {
            'path'      : url_for(".home") + str(report),
            'filename'  : report.filename,
            'project'   : report.project,
            'created'   : report.created,
            'updated'   : report.updated,
            'title'     : report.title
        }
        result.append(item)
    return jsonify(results = result)


@blueprint.route("/<project>/<filename>/", methods=["GET", "POST"])
@validate_project_filename
def display(project, filename):
    report = Report.query.filter_by(filename = filename, project = project).first()
    if report:
        if report.published or (not current_user.is_anonymous() and
            current_user.is_admin):
            return report.html_content
        else:
            raise NotFound()
    else:
        raise NotFound()

@blueprint.route("/<project>/<filename>/edit", methods=["GET", "POST"])
@validate_project_filename
@login_required
@check_admin
def edit(project, filename):
    template_name = request.args.get('template', 'default')
    report = Report.query.filter_by(project = project, filename = filename).first()
    default_template = Template.query.filter_by(name = template_name).first()
    form = None
    if report:
        form = EditorForm(project_field=project, filename_field=filename, 
            template_field = report.template, markdown_field=report.md_content,
            published_field = report.published, listed_field = report.listed)
    else:
        form = EditorForm(project_field=project, filename_field=filename, 
            template_field = default_template, markdown_field=default_template.md_content)
    if request.method == 'POST':
        if form.validate_on_submit():
            save_user = None
            if current_user.is_anonymous():
                save_user = User.query.filter_by(username="<blank>").first()
            else:
                save_user = current_user
            if form.savemode is 'save':
                report = Report.query.filter_by(filename = form.filename, 
                    project = form.project).first()
                if report:
                    report.update(template_id = form.template.id, 
                        md_content = form.md_content,
                        listed = form.listed,
                        published = form.published)
                    flash("Report saved.", 'success')
                else:
                    report = Report.create(filename = form.filename, 
                        project = form.project, template = form.template, 
                        md_content = form.md_content, author = save_user,
                        listed = form.listed, published = form.published)
                    flash("New report created and saved!", 'success')
                report.save_render_html()
                form = EditorForm(project_field=form.project,
                    filename_field=form.filename, template_field=form.template,
                    markdown_field = form.md_content, listed_field = form.listed,
                    published_field = form.published)
            elif form.savemode is "saveas":
                report = Report.create(filename = form.filename, 
                    project = form.project, template = form.template, 
                    md_content = form.md_content, author = save_user,
                    listed = form.listed, published = form.published)
                report.save_render_html()
                old_path = os.path.join(upload_path(), form.old_project,
                    form.old_filename)
                new_path = os.path.join(upload_path(), form.project,
                    form.filename)
                # Move files along with copying data
                try:
                    files = os.listdir(old_path)
                except OSError:
                    pass
                else:
                    if os.path.exists(new_path):
                        flash("Files not copied!", 'error')
                    else:
                        shutil.copytree(old_path, new_path)
                        flash("Files copied!", 'success')
                flash("New report created and saved!", 'success')
                return redirect("/reports/" + form.project + "/" + 
                    form.filename + "/edit", 303)
            else:
                assert False
        else:
            flash_errors(form)
    preview_form = PreviewForm(markdown_preview_field = '', template_preview_field = '')
    return render_template('editor.html',form=form, project=project, 
        filename=filename, preview_form=preview_form)

@blueprint.route("/<project>/<filename>/upload", methods=["POST"])
@validate_project_filename
@login_required
@check_admin
def upload_file(project, filename):
    file = request.files['file']
    if file and allowed_file(file.filename):
        file_save = secure_filename(file.filename)
        try:
            os.makedirs(os.path.join(upload_path(), project, filename))
        except OSError:
            pass
        try:
            file.save(os.path.join(upload_path(), project, filename, file_save))
        except (IOError, OSError) as err:
            raise Conflict("Can't save file: " + err.strerror)
            flash("Can't save file: " + err.strerror, 'error')
        else:
            return "File uploaded", 200   

flask/useradvocacy/user/__init__.py
'''The user module.'''

from . import views

flask/useradvocacy/user/views.py
# -*- coding: utf-8 -*-
from flask import Blueprint, render_template
from flask.ext.login import login_required

blueprint = Blueprint("user", __name__, url_prefix='/users',
                        static_folder="../static")


@blueprint.route("/")
@login_required
def members():
    return render_template("users/members.html")

flask/useradvocacy/templates/401.html
{% extends "layout.html" %}

{% block page_title %}Unauthorized{% endblock %}

{% block content %}
<div class="jumbotron">
    <div class="text-center">
        <h1>401</h1>
        <p>You are not authorized to see this page. Please <a href="{{ url_for('public.login')}}">log in</a>
        <br/>
        or head to the <a href="{{ url_for('public.home')}}">start page</a> to find what you're looking for.
        </p>
    </div>
</div>
{% endblock %}

flask/useradvocacy/templates/footer.html
<footer>
  <small>
  <ul class="company">
    <li></li>
  </ul>

    <ul class="footer-nav">

      <li><a href="{{ url_for('public.about') }}">About</a></li>
      <li><a href="mailto:user-advocacy@mozilla.com">Contact</a></li>
      {% if current_user and current_user.is_authenticated() %}
      {% else %}
      <li><a href="{{ url_for('public.login') }}">Login</a></li>
      {% endif %}
    </ul>
  </small>
</footer>

flask/useradvocacy/templates/layout.html
<!doctype html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<head>
  <meta charset="utf-8">

  <title>{% block page_title %}

    UA Server

    {% endblock %}
  </title>
  <meta name="description" content="{% block meta_description %}{% endblock %}">
  <meta name="author" content="{% block meta_author %}{% endblock %}">

  <!-- Mobile viewport optimized: h5bp.com/viewport -->
  <meta name="viewport" content="width=device-width">

  <link rel="stylesheet" href="{{ url_for('static', filename='libs/font-awesome/css/font-awesome.min.css') }}">
  {% assets "css_all" %}
    <link rel="stylesheet" href="{{ ASSET_URL }}">
  {% endassets %}

  {% block css %}{% endblock %}

</head>
<body class="{% block body_class %}{% endblock %}">
{% block body %}
{% with form=form  %}
{% include "nav.html" %}
{% endwith %}

<header>{% block header %}{% endblock %}</header>
<div class="{% block content_class %}container{% endblock content_class %}">

  <div role="main">
    {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
    <div class="row">
      <div class="col-md-12">
        {% for category, message in messages %}
        <div class="alert alert-{{ category }}">
          <a class="close" title="Close" href="#" data-dismiss="alert">&times;</a>
         {{message}}
        </div><!-- end .alert -->
        {% endfor %}
      </div><!-- end col-md -->
    </div><!-- end row -->
        {% endif %}
    {% endwith %}

    {% block content %}{% endblock %}
  </div>

</div><!-- end container -->

{% include "footer.html" %}

<!-- JavaScript at the bottom for fast page loading -->
{% assets "js_all" %}
    <script type="text/javascript" src="{{ ASSET_URL }}"></script>
{% endassets %}
{% block js %}{% endblock %}
<!-- end scripts -->
{% endblock %}
</body>
</html>

flask/useradvocacy/templates/nav.html
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">

  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="{{ url_for('public.home') }}"><span class="large-grey-text">User</span><span class="large-red-text">Advocacy</span>
    </a>
  </div>
  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse navbar-ex1-collapse">
    <ul class="nav navbar-nav">
      <li><a href="{{ url_for('public.home') }}"><i class="fa fa-home"></i> Home</a></li>
      <li><a href="{{ url_for('reports.home') }}"><i class="fa fa-file-text-o"></i> Reports</a> </li>
      {% if current_user and current_user.is_authenticated() and current_user.is_admin %}
      <li><a href="{{ url_for('reports.selector') }}"><i class="fa fa-edit"> </i> Edit Reports</a></li>
      {% endif %}
      <li> <a href="{{ url_for('dashboards.home') }}"><i class="fa fa-bar-chart"></i> Dashboards</a></li>
    </ul>
    {% if current_user and current_user.is_authenticated() %}
    <ul class="nav navbar-nav navbar-right">
        <li>
            <p class="navbar-text">Logged in as {{ current_user.username }}</p>
        </li>
        <li><a class="navbar-link" href="{{ url_for('public.logout') }}"><i class="fa fa-sign-out"></i></a></li>

    </ul>
    {% elif login_form %}
    {% endif %}
  </div><!-- /.navbar-collapse -->
  </div><!-- /.container -->
</nav>